Update sync-with-remote.yml

diff --git a/.github/workflows/sync-with-remote.yml b/.github/workflows/sync-with-remote.yml
--- a/.github/workflows/sync-with-remote.yml
+++ b/.github/workflows/sync-with-remote.yml
@@ -3,23 +3,26 @@ name: Sync with Remote
 on:
   push:
     branches:
-      - master 
+      - master
 
 jobs:
   sync-with-remote:
     runs-on: ubuntu-latest
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
+      - uses: actions/checkout@v4
+      - name: Verify SSH fingerprint
+        run: |
+          ssh-keyscan -t ec2-user@13.200.152.101 > /tmp/remote_fingerprint
+          if ! cmp /tmp/remote_fingerprint ~/.ssh/known_hosts; then
+            echo "Host key verification failed. Adding server to known_hosts..."
+            ssh-keyscan -t ec2-user@13.200.152.101 >> ~/.ssh/known_hosts
+          fi
       - name: Add SSH key
         uses: webfactory/ssh-agent@v0.5.4
         with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
-
       - name: Add Remote
         run: git remote add production ec2-user@13.200.152.101:/var/www/test/test-repo.git
-
       - name: Push to Remote
-        run: git push production master 
+        run: git push production HEAD
+
